### ISSUE TITLE
when creat new project with wizard , it will  report file not found , I use the version  23.0.0

### ISSUE THREAD

**Issue by wangwei357** [ni/niveristand-custom-device-wizard#49]
**Describe the bug**
when creat new project with wizard , it will  report file not found .  I use the version  23.0.0 and the labview is 2020 .

The report version is below:
LabVIEW: (Hex 0x7) File not found. The file might be in a different location or deleted. Use the command prompt or the file explorer to verify that the path is correct.
VI Path: C:\Program Files (x86)\National Instruments\LabVIEW 2020\project\_Compiled HTML Menu Tool\Wizard\Copy Template Files.vi

_Compiled HTML Menu Tool folder seem that didn't  generation by install step .

![屏幕截图 2023-05-15 143653](https://github.com/ni/niveristand-custom-device-wizard/assets/77340375/cedc646c-5e31-42bb-a3fa-a741b4fd339f)

**Comment by buckd** [comment]
@wangwei357 That directory should be created when you install the [VeriStand Custom Device Development Tools](https://github.com/ni/niveristand-custom-device-development-tools/releases/latest). Have you installed the `ni-veristand-custom-device-development-tools-2020-support_<version>_windows_x64.nipkg` from that repository?

You will also need to install the **HTML Workshop** as noted in the [README](https://github.com/ni/niveristand-custom-device-wizard/blob/main/README.md).

**Comment by wangwei357** [comment]
@buckd  Thanks. You are so kindy.   It's my mistake . I had reinstall them and all is OK now.
